### ISSUE TITLE
'CutinterfaceDialog' object has no attribute 'movie_box'

### ISSUE THREAD

**Issue by timsummerer** [EinApfelBaum/otr-verwaltung3p#103]
Hello,

I have been using otr-verwaltung3p for a while and today I encountered the following exception when trying to manually cut a video.
Since I cleaned up some packages yesterday, I might have removed a dependency accidentally BUT reinstalling otr-verwaltung3p from GitHub and the AUR result in the same exception.
The issue also occured before updating to the latest version and it (probably) also occurs in master.

If you need more info about the packages installed on my system or info about the file I will gladly try to help but this looks like a bug in the CutInterfaceDialog.

Exception:
```
otr-verwaltung3p, version 1.0.0-beta002
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/otrverwaltung3p/gui/widgets/movieBox.py", line 17, in __init__
    self.movie_widget = self.gtksink.props.widget
AttributeError: 'NoneType' object has no attribute 'props'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/otrverwaltung3p/gui/CutinterfaceDialog.py", line 63, in do_parser_finished
    self.movie_box = self.builder.get_object('movie_box').movie_widget
AttributeError: 'MovieBox' object has no attribute 'movie_widget'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/otrverwaltung3p/gui/MainWindow.py", line 753, in _on_toolbutton_clicked
    self.app.perform_action(action, cut_action)
  File "/usr/bin/otrverwaltung3p", line 688, in perform_action
    action.do(chosen_action, filenames, cut_action)
  File "/usr/lib/python3.8/site-packages/otrverwaltung3p/actions/decodeorcut.py", line 85, in do
    if self.cut(file_conclusions, action, cut_action) == False:
  File "/usr/lib/python3.8/site-packages/otrverwaltung3p/actions/decodeorcut.py", line 361, in cut
    error_message, cutlist = self.cut_file_manually(file_conclusion.uncut_video)
  File "/usr/lib/python3.8/site-packages/otrverwaltung3p/actions/decodeorcut.py", line 514, in cut_file_manually
    cutlist = ci._run(filename, local_cutlist, self.app)
  File "/usr/lib/python3.8/site-packages/otrverwaltung3p/gui/CutinterfaceDialog.py", line 171, in _run
    self.movie_box.set_size_request(self.config.get('general', 'cutinterface_resolution_x'),
AttributeError: 'CutinterfaceDialog' object has no attribute 'movie_box'
```

**Comment by gCurse** [comment]
Please install gst-plugin-gtk
They split this out from gst-plugins-good

I'll update the AUR packages. EDIT: Done

Thanks for your report.

**Comment by timsummerer** [comment]
I just updated and installing the dependency fixed the issue. Thanks!
