### ISSUE TITLE
otr-verwaltung3p does not launch on WSL2 Ubuntu 20.04

### ISSUE THREAD

**Issue by timsummerer** [EinApfelBaum/otr-verwaltung3p#110]
Trying to launch otr-verwaltung3p on Ubuntu 20.04 (fully updated) under WSL2 yields the following error.

```
otr-verwaltung3p, version 1.0.0b8.post4
E:config:Config:load:141 Config file is not available. ([Errno 2] No such file or directory: '/home/tim/.config/otrverwaltung3p/conf') Using default configuration.
Traceback (most recent call last):
  File "/usr/bin/otrverwaltung3p", line 1267, in <module>
    app = App()
  File "/usr/bin/otrverwaltung3p", line 358, in __init__
    self.__gui = gui.Gui(self)  # for backwards compability
  File "/usr/lib/python3/dist-packages/otrverwaltung3p/gui/gui.py", line 57, in __init__
    self.main_window.post_init()
  File "/usr/lib/python3/dist-packages/otrverwaltung3p/gui/MainWindow.py", line 79, in post_init
    self.__setup_toolbar()
  File "/usr/lib/python3/dist-packages/otrverwaltung3p/gui/MainWindow.py", line 163, in __setup_toolbar
    image.show()
UnboundLocalError: local variable 'image' referenced before assignment
```

Tutorial used to set up WSL2 for GUI apps: [https://techcommunity.microsoft.com/t5/windows-dev-appconsult/running-wsl-gui-apps-on-windows-10/ba-p/1493242](this)

glxgears runs fine when disabling native openGL at launch of XLaunch.
gedit also works as expected.

otr-verwaltung3p was installed using `dpkg -i` followed by `apt install -f`

**Comment by gCurse** [comment]
That is tricky.
Please start otrv with the parameter `-v` and post the terminal output.

**Comment by timsummerer** [comment]
The output of `otrverwaltung3p -v` from the WSL terminal is

```
I:backend:keyring.backend:_load_plugins:193 Loading KWallet
I:backend:keyring.backend:_load_plugins:193 Loading SecretService
I:backend:keyring.backend:_load_plugins:193 Loading Windows
I:backend:keyring.backend:_load_plugins:193 Loading chainer
I:backend:keyring.backend:_load_plugins:193 Loading macOS
otr-verwaltung3p, version 1.0.0b8.post4
I:MainWindow:otrverwaltung3p.gui.MainWindow:new:940 Version: 1.0.0b8.post4
I:MainWindow:MainWindow:__setup_toolbar:161 gtk-icon-theme-error-quark: Icon 'edit-cut' not present in theme Yaru (0)
Traceback (most recent call last):
  File "/usr/bin/otrverwaltung3p", line 1267, in <module>
    app = App()
  File "/usr/bin/otrverwaltung3p", line 358, in __init__
    self.__gui = gui.Gui(self)  # for backwards compability
  File "/usr/lib/python3/dist-packages/otrverwaltung3p/gui/gui.py", line 57, in __init__
    self.main_window.post_init()
  File "/usr/lib/python3/dist-packages/otrverwaltung3p/gui/MainWindow.py", line 79, in post_init
    self.__setup_toolbar()
  File "/usr/lib/python3/dist-packages/otrverwaltung3p/gui/MainWindow.py", line 163, in __setup_toolbar
    image.show()
UnboundLocalError: local variable 'image' referenced before assignment
```

I also noticed the program works as expected if I run `startxfce4` and launch it from there. Probably the environment is not set up to the needs of the application.
Running `otrverwaltung3p -v` from `gnome-terminal` launched from xfce yields

```
I:backend:keyring.backend:_load_plugins:193 Loading KWallet
I:backend:keyring.backend:_load_plugins:193 Loading SecretService
I:backend:keyring.backend:_load_plugins:193 Loading Windows
I:backend:keyring.backend:_load_plugins:193 Loading chainer
I:backend:keyring.backend:_load_plugins:193 Loading macOS
otr-verwaltung3p, version 1.0.0b8.post4
I:MainWindow:otrverwaltung3p.gui.MainWindow:new:940 Version: 1.0.0b8.post4
I:MainWindow:MainWindow:__setup_toolbar:161 gtk-icon-theme-error-quark: Icon 'edit-rename' not present in theme elementary-xfce-dark (0)
I:pluginsystem:PluginSystem:__init__:71 Paths to search: ('/home/tim/.local/share/otrverwaltung3p/plugins', '/usr/share/otrverwaltung3p/plugins')
I:pluginsystem:PluginSystem:__init__:75 /home/tim/.local/share/otrverwaltung3p/plugins is not a directory.
I:pluginsystem:PluginSystem:__init__:102 Found: Mediainfo
I:pluginsystem:PluginSystem:__init__:102 Found: CutPlay
I:pluginsystem:PluginSystem:__init__:102 Found: Play
I:pluginsystem:PluginSystem:__init__:102 Found: ConvertToMP3
I:pluginsystem:PluginSystem:__init__:102 Found: Mkv
I:pluginsystem:PluginSystem:__init__:102 Found: CutManually
I:pluginsystem:PluginSystem:__init__:102 Found: MP4
I:pluginsystem:PluginSystem:__init__:110 Enabled: Play
I:pluginsystem:PluginSystem:__init__:110 Enabled: Mkv
```

**Comment by gCurse** [comment]
Sorry, WSL is not supported. Still, I made a fix that may be published.
