### ISSUE TITLE
AttributeError in actions/cut.py

### ISSUE THREAD

**Issue by robertschulze** [EinApfelBaum/otr-verwaltung3p#111]
Leider funktioniert bei mir seit neuestem (ws. ein Update eines Python-Pakets) das Schneiden nicht mehr:

```
D:config:Config:get:68 [general][server]: http://cutlist.at/
D:config:Config:get:68 [general][choose_cutlists_by]: 1
D:config:Config:get:68 [general][cutlist_mp4_as_hq]: False
D:cutlists:otrverwaltung.cutlists:download_cutlists:336 Download from : http://cutlist.at/getxml.php?name=Ostwind_III_Aufbruch_nach_Ora_20.12.27_05-30_ard_100_TVOON_DE.mpg.HD
D:cutlists:otrverwaltung.cutlists:__read_value:404 Reading node rating failed. Returning empty string.
D:cutlists:otrverwaltung.cutlists:__read_value:404 Reading node actualcontent failed. Returning empty string.
D:cutlists:otrverwaltung.cutlists:__read_value:404 Reading node othererrordescription failed. Returning empty string.
D:cutlists:otrverwaltung.cutlists:__read_value:404 Reading node autoname failed. Returning empty string.
D:config:Config:get:68 [general][server]: http://cutlist.at/
D:config:Config:get:68 [general][choose_cutlists_by]: 1
D:config:Config:get:68 [general][cutlist_mp4_as_hq]: False
D:cutlists:otrverwaltung.cutlists:download_cutlists:336 Download from : http://cutlist.at/getxml.php?name=Ostwind_III_Aufbruch_nach_Ora_20.12.27_05-30_ard_100_TVOON_DE.mpg.HD
D:cutlists:otrverwaltung.cutlists:__read_value:404 Reading node rating failed. Returning empty string.
D:cutlists:otrverwaltung.cutlists:__read_value:404 Reading node actualcontent failed. Returning empty string.
D:cutlists:otrverwaltung.cutlists:__read_value:404 Reading node othererrordescription failed. Returning empty string.
D:cutlists:otrverwaltung.cutlists:__read_value:404 Reading node autoname failed. Returning empty string.
I:decodeorcut:DecodeOrCut:cut:392 [Decodeandcut] Datei /home/robert/otr/2-decoded/Ostwind_III_Aufbruch_nach_Ora_20.12.27_05-30_ard_100_TVOON_DE.mpg.HD.avi wird geschnitten
D:config:Config:get:68 [general][server]: http://cutlist.at/
D:config:Config:get:68 [general][cut_avis_by]: SmartMKVmerge
D:config:Config:get:68 [general][cut_hqs_by]: SmartMKVmerge
D:config:Config:get:68 [general][cut_hqs_by]: SmartMKVmerge
D:config:Config:get:68 [general][cut_mp4s_by]: SmartMKVmerge
D:cut:DecodeOrCut:get_format:64 function start
I:cutlists:Cutlist:read_cuts:202 Append frames: 21661, 302526
I:cutlists:Cutlist:read_cuts:208 Append seconds:  433.22, 6050.52
D:config:Config:get:68 [smartmkvmerge][workingdir]: /tmp
D:config:Config:get:68 [smartmkvmerge][workingdir]: /tmp
D:config:Config:get:68 [smartmkvmerge][workingdir]: /tmp
D:config:Config:get:68 [smartmkvmerge][workingdir]: /tmp
D:cutsmartmkvmerge:CutSmartMkvmerge:cut_file_by_cutlist:89 FFMPEG: /home/robert/otr/otr-verwaltung3p/otrverwaltung/../data/tools/intern-ffmpeg
D:config:Config:get:68 [smartmkvmerge][encoder_engine]: ffmpeg
D:cut:CutSmartMkvmerge:analyse_mediafile:303 FPS: 50.0
D:cut:CutSmartMkvmerge:analyse_mediafile:315 Leave function
D:cut:CutSmartMkvmerge:get_format:64 function start
D:config:Config:get:68 [smartmkvmerge][ffmpeg_hd_x264_options]: crf=23:deblock=-1/-1:psy-rd=1/0.15:direct=auto:force-cfr=1:b-adapt=2:rc-lookahead=60:weightp=0:aq-mode=2
D:cut:CutSmartMkvmerge:analyse_mediafile:303 FPS: 50.0
D:cut:CutSmartMkvmerge:analyse_mediafile:315 Leave function 
Traceback (most recent call last):
  File "/home/robert/otr/otr-verwaltung3p/otrverwaltung/gui/MainWindow.py", line 740, in _on_toolbutton_clicked
    self.app.perform_action(action, cut_action)
  File "./otrverwaltung", line 679, in perform_action
    action.do(chosen_action, filenames, cut_action)
  File "/home/robert/otr/otr-verwaltung3p/otrverwaltung/actions/decodeorcut.py", line 82, in do
    if self.cut(file_conclusions, action, cut_action) == False:
  File "/home/robert/otr/otr-verwaltung3p/otrverwaltung/actions/decodeorcut.py", line 402, in cut
    cut_video, ac3_file, error = self.cut_file_by_cutlist(file_conclusion.uncut_video,
  File "/home/robert/otr/otr-verwaltung3p/otrverwaltung/actions/decodeorcut.py", line 543, in cut_file_by_cutlist
    cut_video, error = cutter.cut_file_by_cutlist(filename, cutlist)
  File "/home/robert/otr/otr-verwaltung3p/otrverwaltung/actions/cutsmartmkvmerge.py", line 116, in cut_file_by_cutlist
    codec, codec_core = self.ffmpeg_codec_options(
  File "/home/robert/otr/otr-verwaltung3p/otrverwaltung/actions/cut.py", line 591, in ffmpeg_codec_options
    codec_core = int(self.media_info.tracks[1].writing_library.split(' ')[2])
AttributeError: 'NoneType' object has no attribute 'split'
```
Leider sagt mir der Fehler garnichts.

**Comment by DrVanScott** [comment]
I experienced the same issue after first trying to use the cloned repository and installing via "installscript". After I installed the provided deb from https://www.otrforum.com/showthread.php?74447-OTRVerwaltung3Plus-eine-Portierung-von-OTRVerwaltung-hinzu-Python3-und-Gtk3&p=420125&viewfull=1#post420125 the issue dissapeared

**Comment by gCurse** [comment]
[Newest deb releases](https://github.com/EinApfelBaum/otr-verwaltung3p/releases). The topmost is the newest.

[Installation scripts](https://github.com/gCurse/support/tree/master/otrv3p_installation_scripts). Only use files with "dev" in the filename for now.

@DrVanScott : Please do not link to otrforum.com for downloads. Use direct links, please.

**Comment by robertschulze** [comment]
Indeed, using the newest release it is working. Thanks!
