### ISSUE TITLE
Does not launch

### ISSUE THREAD

**Issue by noyannus** [EinApfelBaum/otr-verwaltung3p#121]
Ov3p stopped working recently; two weeks ago I could use it, now it won't launch, even with fresh installs of 
```
otr-verwaltung3p-dev	1.0.0b8.post5-11	from AUR
otr-verwaltung3p-vdub	1.0.0-1				from AUR
```
in Manjaro
KDE Plasma 5.26.5
KDE Frameworks 5.103.0
Kernel 6.1.19-1-MANJARO (64-bit).

An attempt to starting ov3p from launcher briefly shows a bouncing icon of ov3p, then nothing more.

CLI command throws an error:
```
$ pwd
/home/<user>
$ python --version 
Python 3.10.9
$ otrverwaltung3p
Traceback (most recent call last):
File "/usr/bin/otrverwaltung3p", line 118, in <module>
from otrverwaltung3p.actions import actions
File "/usr/lib/python3.10/site-packages/otrverwaltung3p/actions/actions.py", line 18, in <module>
from otrverwaltung3p.actions import decodeorcut
File "/usr/lib/python3.10/site-packages/otrverwaltung3p/actions/decodeorcut.py", line 34, in <module>
from otrverwaltung3p.actions.cut import Cut
File "/usr/lib/python3.10/site-packages/otrverwaltung3p/actions/cut.py", line 36, in <module>
from otrverwaltung3p.libs.pymediainfo import MediaInfo
File "/usr/lib/python3.10/site-packages/otrverwaltung3p/libs/pymediainfo/__init__.py", line 21, in <module>
__version__ = get_distribution("pymediainfo").version
File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 514, in get_distribution
dist = get_provider(dist)
File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 386, in get_provider
return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 956, in require
needed = self.resolve(parse_requirements(requirements))
File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 815, in resolve
dist = self._resolve_dist(
File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 844, in _resolve_dist
env = Environment(self.entries)
File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1044, in __init__
self.scan(search_path)
File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1077, in scan
self.add(dist)
File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1096, in add
dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2639, in hashcmp
self.parsed_version,
File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2693, in parsed_version
raise packaging.version.InvalidVersion(f"{str(ex)} {info}") from None
packaging.version.InvalidVersion: Invalid version: '2.10.1.Ludicrous.Lemur' (package: Shredder)
```

**Comment by gCurse** [comment]
https://bbs.archlinux.org/viewtopic.php?pid=2086931#p2086931
Schon versucht?

**Comment by noyannus** [comment]
> [bbs.archlinux.org/viewtopic.php?pid=2086931#p2086931](https://bbs.archlinux.org/viewtopic.php?pid=2086931#p2086931) Schon versucht?

Klappt. Danke!
Schönes Wochenende!
