### ISSUE TITLE
trying to manual cut ends in [intern-ffmsinde] <defunct>

### ISSUE THREAD

**Issue by fermat2a** [EinApfelBaum/otr-verwaltung3p#73]
Hi,

I updated yesterday to version 3.3.0-A (commit 76ba16471c5f9fc986e639b044fb2bfdac2f42c9, this is head of master up to now). Try to cut a movie manually the gui shows "Datei wird indiziert" with a progress bar stopping somewhere and nothing else happens (even waiting for 10 Minutes, I was getting a coffee when I tried first time). In the process list I see that otr-verwaltung3p spawned a process, which is defunct:

```
fermat   22712  2046  0 09:09 tty2     00:00:03 python3 /home/fermat/otr-verwaltung3p/bin/otrverwaltung
fermat   23031 22712  0 09:11 tty2     00:00:02 [intern-ffmsinde] <defunct>
```

I am running it in Ubuntu 18.04 x86_64.

Do you have an idea how I can find out what is going wrong?

bests

Sascha

**Comment by fermat2a** [comment]
The described behaviour seems to happen only when I try to cut _Griessnockerlaffaere_18.08.07_02-10_ard_90_TVOON_DE.mpg.HD.avi_. For another File _Wild_Target_Sein_schaerfstes_Ziel_18.08.09_00-20_ard_93_TVOON_DE.mpg.HD.avi_ it just goes back to the main screen and I it sows "Cutlist 1/1 wählen" at the lower right side, even if the dialog is no more there. Here I get the following output at the shell:

```
Traceback (most recent call last):
  File "/home/fermat/otr-verwaltung3p/otrverwaltung/gui/widgets/gstBox.py", line 19, in __init__
    self.swidget = self.gtksink.props.widget
AttributeError: 'NoneType' object has no attribute 'props'
Traceback (most recent call last):
  File "/home/fermat/otr-verwaltung3p/otrverwaltung/gui/CutinterfaceDialog.py", line 70, in do_parser_finished
    self.movie_window = self.builder.get_object('gst_box').swidget
AttributeError: 'GstBox' object has no attribute 'swidget'
Traceback (most recent call last):
  File "/home/fermat/otr-verwaltung3p/otrverwaltung/gui/MainWindow.py", line 736, in _on_toolbutton_clicked
    self.app.perform_action(action, cut_action)
  File "./bin/otrverwaltung", line 675, in perform_action
    action.do(chosen_action, filenames, cut_action)
  File "/home/fermat/otr-verwaltung3p/otrverwaltung/actions/decodeorcut.py", line 82, in do
    if self.cut(file_conclusions, action, cut_action) == False:
  File "/home/fermat/otr-verwaltung3p/otrverwaltung/actions/decodeorcut.py", line 339, in cut
    error_message, cutlist = self.cut_file_manually(file_conclusion.uncut_video)
  File "/home/fermat/otr-verwaltung3p/otrverwaltung/actions/decodeorcut.py", line 486, in cut_file_manually
    cutlist = ci._run(filename, local_cutlist, self.app)
  File "/home/fermat/otr-verwaltung3p/otrverwaltung/gui/CutinterfaceDialog.py", line 174, in _run
    self.movie_window.set_size_request(self.config.get('general', 'cutinterface_resolution_x'),
AttributeError: 'CutinterfaceDialog' object has no attribute 'movie_window'
```

I also tried with HEAD~1 (so the one containing the tag 3.3.0.A), same result.

**Comment by gCurse** [comment]
Seems `gtksink` is not available on your system. Seems your're using Ubuntu. Please install `gstreamer1.0-gtk3`.
