### ISSUE TITLE
Missing lib.pymediainfo in v3.3.1-A

### ISSUE THREAD

**Issue by mmo442** [EinApfelBaum/otr-verwaltung3p#75]
The file otr-verwaltung3p/lib/pymediainfo.py is missing in version v3.3.1-A.

```
$ bin/otrverwaltung
Traceback (most recent call last):
  File "bin/otrverwaltung", line 110, in <module>
    from otrverwaltung.actions import actions
  File "otrverwaltung/actions/actions.py", line 17, in <module>
    from otrverwaltung.actions import decodeorcut
  File "otrverwaltung/actions/decodeorcut.py", line 32, in <module>
    from otrverwaltung.gui import CutinterfaceDialog
  File "otrverwaltung/gui/CutinterfaceDialog.py", line 24, in <module>
    from otrverwaltung.actions.cut import Cut
  File "otrverwaltung/actions/cut.py", line 27, in <module>
    from lib.pymediainfo import MediaInfo
ModuleNotFoundError: No module named 'lib'
$
```

**Comment by gCurse** [comment]
[0301f4b](https://github.com/EinApfelBaum/otr-verwaltung3p/commit/0301f4b94c3dc7ee6b0d182c2943d175210f1c67) should fix this.
