### ISSUE TITLE
ImportError: /usr/lib/x86_64-linux-gnu/libboost_python27.so.1.67.0: undefined symbol: PyString_Type

### ISSUE THREAD

**Issue by timo08** [EinApfelBaum/otr-verwaltung3p#80]
At start of otr-verwaltung3p i get the given error on my debian 10 (buster) system:

Traceback (most recent call last):
  File "./bin/otrverwaltung", line 110, in <module>
    from otrverwaltung.actions import actions
  File "/home/user/otr-verwaltung3p/otrverwaltung/actions/actions.py", line 21, in <module>
    from otrverwaltung.actions import download
  File "/home/user/otr-verwaltung3p/otrverwaltung/actions/download.py", line 22, in <module>
    from otrverwaltung.gui import AddDownloadDialog
  File "/home/user/otr-verwaltung3p/otrverwaltung/gui/AddDownloadDialog.py", line 17, in <module>
    import libtorrent as lt
ImportError: /usr/lib/x86_64-linux-gnu/libboost_python27.so.1.67.0: undefined symbol: PyString_Type

I can not solve this problem.
Tried to install different versions of libboost-python1.67.0, same problem.
Also tried in a virtual machine with a fresh kali system. Same problem.

**Comment by gCurse** [comment]
Strange that python 2.7 is involved.
